# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
#            config.build_settings['SWIFT_VERSION'] = "4.2"
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end

def shared_pods
    pod 'Swinject'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'IQKeyboardManager'
    pod 'Kingfisher'
    pod 'Toaster'
    pod 'AlamofireNetworkActivityLogger'
    pod 'AlamofireActivityLogger'
    pod 'NVActivityIndicatorView'
end


target 'MapDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  shared_pods

  # Pods for MapDemo

  target 'MapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapDemoUITests' do
    # Pods for testing
  end

end
